# Generated by Django 2.1.1 on 2018-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0003_auto_20180901_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='turno',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
