# Generated by Django 2.1.1 on 2018-09-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0004_modulo_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['prioridad']},
        ),
    ]
